<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>emage_motor_driver</name>
  <version>0.0.1</version> <!-- Update this to a more appropriate version -->
  <description>TODO: Package description</description>
  <maintainer email="deepak@todo.todo">deepak</maintainer>
  <license>TODO: License declaration</license>

  <!-- Build dependencies -->
  <buildtool_depend>ament_cmake</buildtool_depend>
  <build_depend>ament_cmake_ros</build_depend>
  <build_depend>rclpy</build_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>nav_msgs</build_depend>
  <build_depend>tf2_ros</build_depend>
  <build_depend>tf_transformations</build_depend>

  <!-- Runtime dependencies -->
  <exec_depend>triorb_core</exec_depend>
  <exec_depend>tf-transformations</exec_depend>


  <!-- Testing dependencies -->
  <test_depend>ament_lint</test_depend>
  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
